// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tourism.Infrastructure.Persistence;

#nullable disable

namespace Tourism.Infrastructure.Migrations
{
    [DbContext(typeof(TourismDbContext))]
    partial class TourismDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tourism.Domain.Organizations.TourismOrganizationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("BadgeAssessedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BadgeReasons")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("CurrentBadge")
                        .HasColumnType("int");

                    b.Property<Guid?>("LastEvaluationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastProofOfLifeAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ProfileType")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("IX_TourismOrganizationProfiles_OrganizationId");

                    b.ToTable("TourismOrganizationProfiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
